Created team member component
oliviaportess/fullstack-6 pull request #15
Opened 2024-08-06 15:26 UTC by dalpao

- Also added .DS_Store to the .gitignore at the root of the project

2024-08-06 15:49 UTC, soojinhwang reviewed
Hi Paola, did you pull from the staging branch before you started creating these?
Because Phoebe already created a "utils" folder inside the "src" folder yesterday where we should be putting all the components in, so I think adding another folder called "components" is going to be confusing in the long-run

2024-08-06 15:57 UTC, soojinhwang requested changes
I think also it would be good to separate out the TeamMember component into a separate smaller component, and then create another component/page for About Us and use props.
 
 So something more like this (according to ChatGPT) for the team member component:
 
![image](https://github.com/user-attachments/assets/c9c2475c-9a3d-4bc6-bc29-8e80d4058e46)

2024-08-07 10:11 UTC, dalpao commented
I have renamed the components with capital letters, removed the package-lock.json at the top level of the repo, and moved the utils folder inside the src folder. I will refactor the Team.js component once I create the About.js component.

2024-08-07 16:17 UTC, soojinhwang approved these changes

2024-08-07 18:14 UTC, oliviaportess approved these changes

2024-08-07 20:11 UTC, merged