User Score component created
oliviaportess/fullstack-6 pull request #31
Opened 2024-08-12 13:45 UTC by RayahRahman

2024-08-12 14:15 UTC, jacquelyn-bradshaw approved these changes

2024-08-12 17:49 UTC, oliviaportess requested changes
Hi Rayah,

Please can you amend the PR to merge into staging rather than into main

Also, looks like the file structure has changed quite a bit since you last git pulled from the remote repo. For example we no longer have the 'utils' folder, so I think this might cause issues if we tried to merge your code. I think it would work better if you git pulled from staging, then added your new files into the 'components' folder. Hope that makes sense! The files themselves look good to me though :)

2024-08-12 17:58 UTC, soojinhwang requested changes
Agree with Olivia's points
I think also you might need to rename your files UserScore.js and UserScore.css as Isslem mentioned previously in the lectures that you can't export them they're named in that format

I also made the mistake of making a pull request to main before, but I couldn't edit the PR and had to make a new one to merge to testing FYI

2024-08-21 17:59 UTC, closed without merging

2024-08-21 18:00 UTC, jacquelyn-bradshaw commented
New pull request was made