Feature/g6 6/raniarayahusercomponent
oliviaportess/fullstack-6 pull request #46
Opened 2024-08-15 13:13 UTC by raniab1903

separated components, created scoreboard page.

2024-08-15 13:47 UTC, jacquelyn-bradshaw requested changes
Please can you run `npm lint-fix` in your terminal from the client directory

2024-08-15 13:47 UTC, jacquelyn-bradshaw commented on client/src/components/UserScore.js
> +import React from 'react';
This is your scoreboard page, it just needs renaming to ScoreboardPage.js and putting in the pages folder

2024-08-15 13:47 UTC, jacquelyn-bradshaw commented on client/src/pages/ScoreboardPage.js
> +import React from 'react';
this page is not needed

2024-08-15 13:47 UTC, jacquelyn-bradshaw commented on client/src/components/UserScore.css
> +  h2 {
this h2 needs to be a class because of how react compiles behind the scenes

2024-08-15 13:47 UTC, jacquelyn-bradshaw commented on userscore.js
> +import React from 'react';
this component is not needed

2024-08-15 16:34 UTC, oliviaportess submitted a review, later dismissed
Hey guys, there are Button.js and MainHeading.js components that we are using to keep design consistent across all pages, I don't think I can see them in your files at the moment? If you aren't using them yet please could you add them.
Let me know if you need info on what they are/how to use them!

2024-08-15 16:38 UTC, soojinhwang commented
+ Olivia's comments with the Navbar and the Background screen components
If you have a look at how the other pages have been set up and their file structure (LandingPage is probably the easiest to get) then you'll be able to see how to incorporate the components that have already been made

2024-08-17 13:06 UTC, jacquelyn-bradshaw commented
> Hey guys, there are Button.js and MainHeading.js components that we are using to keep design consistent across all pages, I don't think I can see them in your files at the moment? If you aren't using them yet please could you add them. Let me know if you need info on what they are/how to use them!

This change is no longer needed as I have added these components to App.js

2024-08-17 13:09 UTC, jacquelyn-bradshaw commented on userscore.js
This whole file is not needed and can be deleted

2024-08-17 13:10 UTC, jacquelyn-bradshaw commented on client/src/pages/ScoreBoardPage.css
> +  h2 {
This will style all h2 elements across the entire app. Please replace h2 tag with a class selector.

2024-08-21 15:27 UTC, oliviaportess approved these changes

2024-08-21 17:59 UTC, jacquelyn-bradshaw approved these changes

2024-08-21 18:04 UTC, merged